# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a vector with values ranging from 10 to 49

In [4]:
vector = np.random.uniform(low=10,high=49, size=10)
vector

array([29.5291891 , 36.96798083, 26.72876774, 40.04977385, 26.1415112 ,
       47.16669249, 10.78596744, 27.49783382, 32.05371771, 24.46986085])

4. Find the shape of previous array in question 3

In [5]:
vector.shape

(10,)

5. Print the type of the previous array in question 3

In [6]:
vector.dtype

dtype('float64')

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
None


7. Print the dimension of the array in question 3


In [8]:
vector.ndim

1

8. Create a boolean array with all the True values

In [9]:
array = np.ones((2,2),dtype=int)
array

array([[1, 1],
       [1, 1]])

9. Create a two dimensional array




In [10]:
array = np.random.randn(3,3)
array

array([[-0.24619777,  1.26139243, -0.82950602],
       [ 0.43106348,  0.31336827,  0.05636519],
       [ 0.72069218,  0.06581993,  0.80224926]])

10. Create a three dimensional array



In [11]:
array = np.random.randn(3,3,3)
array

array([[[ 0.27645011, -1.49202691, -1.70408038],
        [ 0.37967371,  0.10774864, -0.35273426],
        [ 0.70110549,  0.70897232,  0.66662953]],

       [[-1.68141103, -0.85615775,  1.38021288],
        [ 0.45257726, -0.76568088, -0.83226296],
        [-0.62525628, -0.1512123 , -0.90759057]],

       [[ 1.95099391,  1.1433016 ,  0.26872937],
        [-1.00879885,  0.86982261, -0.50372753],
        [ 0.64560465,  0.37184529,  1.07591717]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
vector = np.arange(10,dtype=int)
vector[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
vector = np.eye(10)[5-1]
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [14]:
matrix = np.identity(3,dtype=int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
result = arr1 * arr2
result

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
array = np.arange(10)
res = array[array%2 !=0]
res

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
array = np.arange(10)
np.where(array%2!=0,-1,array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[4]=arr[5]=arr[6]=arr[7]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[arr2d==5]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [25]:
array = np.random.randint(low = 0, high = 9, size = (3,4))
print(array)
array[0, 0:]

[[4 6 8 8]
 [5 0 6 6]
 [1 8 5 3]]


array([4, 6, 8, 8])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [28]:
array = np.random.randint(low = 0, high = 9, size = (3,4))
print(array)
array[1, 1]

[[7 6 3 1]
 [3 4 8 1]
 [5 4 8 7]]


4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [31]:
array = np.random.randint(low = 0, high = 9, size = (3,4))
print(array)
array[:2, 2]

[[1 2 8 4]
 [6 6 4 5]
 [1 8 1 3]]


array([8, 4])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [33]:
array = np.random.randn(10,10)
maxvalue = array.max()
minvalue = array.min()
print(maxvalue,minvalue)

2.0547746707897314 -3.054773892501553


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [37]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [38]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
print(c)

(array([1, 3, 5, 7]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[~(names == "Will")]

array([[ 0.92078815, -0.64176539,  0.89730932, -0.8211888 ],
       [ 1.462202  , -0.82926057, -0.60993038, -0.79804305],
       [ 0.11876891, -1.0699267 , -0.51483405,  1.18630976],
       [ 0.18244724, -0.97831634, -0.41036465,  0.73504344],
       [-0.87528702,  0.65130431,  1.12465865, -0.65552225]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask = (names == "Will")|(names == "Joe")
data[~mask]

array([[ 0.39323182, -1.93180915, -0.82480233,  1.38332496],
       [-0.69066636,  0.44505263,  0.13678022, -1.05471602]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [49]:
arr = np.random.randint(low=1,high=15,size=(5,3),dtype=int)
arr

array([[13, 11,  4],
       [ 5,  2,  8],
       [ 5,  2, 14],
       [10, 14,  8],
       [14,  6,  4]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [50]:
arr = np.random.randint(low=1,high=16,size=(2,2,4),dtype=int)
arr

array([[[ 2, 12,  9,  3],
        [13, 11, 13,  7]],

       [[14,  6, 15,  8],
        [14, 13, 14, 11]]])

33. Swap axes of the array you created in Question 32

In [52]:
arr.swapaxes(1,2)

array([[[ 2, 13],
        [12, 11],
        [ 9, 13],
        [ 3,  7]],

       [[14, 14],
        [ 6, 13],
        [15, 14],
        [ 8, 11]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [53]:
arr = np.random.random(10)
res = np.where(np.sqrt(arr)<0.5,0,arr)
print(arr,res)

[0.80134146 0.41875043 0.82462093 0.58434213 0.28409326 0.31455498
 0.73181003 0.00759048 0.52235073 0.57318599] [0.80134146 0.41875043 0.82462093 0.58434213 0.28409326 0.31455498
 0.73181003 0.         0.52235073 0.57318599]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [54]:
arr1 = np.random.randint(low=1,high=12)
arr2 = np.random.randint(low=1,high=12)
np.maximum(a,b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = np.unique(names)
names.sort()
names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [58]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [60]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1] = newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [61]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [63]:
matrix = np.random.randn(20)
csum = matrix.cumsum()
csum

array([-1.59875838, -2.42048052, -2.51345967, -1.91579156, -2.22716446,
       -4.08058571, -2.9450057 , -3.35905988, -3.73164643, -4.59468617,
       -6.44021966, -6.4696809 , -6.37956194, -5.59466157, -5.74466829,
       -6.05166012, -5.21171385, -3.76062863, -4.38125339, -2.46461889])