# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
data = np.arange(10)
data = data.reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [15]:
data1 = np.arange(10).reshape(2,5)
data2 = np.arange(10,20).reshape(2,5)
print(np.vstack((data1,data2)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
data1 = np.arange(10).reshape(2,5)
data2 = np.arange(10,20).reshape(2,5)
print(np.hstack((data1,data2)))

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [8]:
data = np.arange(20).reshape(4,5)
print(data)
print(data.ravel())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
import numpy as np
data = np.arange(18).reshape(3,3,2)
print(data)
print(data.ravel())

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
data = np.arange(18)
data = data.reshape(3,3,2)
data

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [21]:
a = np.random.rand(5,5)*100
print(np.square(a))

[[4133.01010181 5955.02406038 1879.45831456  571.7738267   826.97777175]
 [1518.20249002 2277.92124147  304.04856255  210.16876617 6093.62809467]
 [8055.22135216 3296.93494306 4084.70085789 6236.40557342 3555.68277479]
 [3878.40949148   23.91312213   15.18306281 2482.53681288 2887.50533675]
 [1023.34701846  124.56154854   67.47737533 2988.49978542 5352.43876571]]


## Question:8

### Create 5x6 an array and find the mean?

In [24]:
data = np.random.randint(1,9, size=(5,6))
print(data)

[[2 8 3 2 2 5]
 [1 2 6 7 7 1]
 [1 2 3 8 3 3]
 [5 6 8 4 8 6]
 [6 6 1 4 3 2]]


In [25]:
print(np.mean(data))

4.166666666666667


## Question:9

### Find the standard deviation of the previous array in Q8?

In [27]:
data = np.random.randint(1,9,size=(5,6))
print(np.std(data))

2.1959558789334137


## Question:10

### Find the median of the previous array in Q8?

In [28]:
data = np.random.randint(1,9,size=(5,6))
print(np.median(data))

4.0


## Question:11

### Find the transpose of the previous array in Q8?

In [30]:
data = np.random.randint(1,9,size=(5,6))
print(data)
print(data.transpose())

[[7 4 3 5 7 1]
 [1 6 6 1 8 4]
 [8 1 8 3 3 5]
 [2 6 4 8 2 8]
 [4 8 3 5 1 3]]
[[7 1 8 2 4]
 [4 6 1 6 8]
 [3 6 8 4 3]
 [5 1 3 8 5]
 [7 8 3 2 1]
 [1 4 5 8 3]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [32]:
data = np.random.randint(1,9,size=(4,4))
print(data,np.trace(data))

[[4 3 7 1]
 [5 1 4 4]
 [5 6 3 5]
 [5 3 7 3]] 11


## Question:13

### Find the determinant of the previous array in Q12?

In [33]:
data = np.random.randint(1,9,size=(4,4))
print(np.linalg.det(data))

-650.9999999999998


## Question:14

### Find the 5th and 95th percentile of an array?

In [38]:
import numpy as np
data = np.arange(100)
print(np.percentile(data,5))
print(np.percentile(data,95))

4.95
94.05


## Question:15

### How to find if a given array has any null values?

In [40]:
a = np.identity(3)
a[0,0] = None
print(np.isnan(a))

[[ True False False]
 [False False False]
 [False False False]]
